### ISSUE TITLE
 implode(): Invalid arguments passed in  on line 110

### ISSUE THREAD

**Issue by mcagri33** [flagshipcompany/flagship-for-opencart#9]
i have a issue for opencart 3.0.2.0 

Warning: implode(): Invalid arguments passed in public_html/catalog/model/extension/shipping/flagship.php on line 110

`
foreach ($rates as $rate) {

            $courierDescription =  strcasecmp($rate->service->courier_name, 'fedex') === 0 ? 'Fedex ' . $rate->service->courier_desc : $rate->service->courier_desc;

            $ratesArray[] = in_array($courierDescription, $selectedRates) == 1 ? $rate : NULL;

        }
`

**Comment by radua** [comment]
Hello @mcagri33 Can you please send an email to developers@flagshipcompany.com with the api token that you are using.
